apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: reencrypt-tls
  labels:
    f5cr: "true"
  namespace: openshift-ingress
spec:
  tls:
    termination: reencrypt
    clientSSL: /Common/clientssl
    serverSSL: /Common/serverssl
    reference: bigip
  hosts:
  - hello-world.example.com
---
apiVersion: cis.f5.com/v1
kind: VirtualServer
metadata:
  name: hello-world-vs
  namespace: openshift-ingress
  labels:
    f5cr: "true"
spec:
  host: hello-world.example.com
  tlsProfileName: reencrypt-tls  # --> This will attach reencrypt-tls TLSProfile
  virtualServerAddress: "10.0.1.101"
  httpTraffic: redirect
  pools:
    - path: /
      monitors:
        #- name: /Common/https
        #  reference: bigip
        - type: https
          send: "GET / HTTP/1.1\r\nHost: hello-world.example.com\r\nConnection: close\r\n\r\n"
          recv: ""
          interval: 10
          timeout: 30
      multiClusterServices:
        # CIS supports to refer svs from local cluster and ha cluster
        - clusterName: cluster1
          namespace: openshift-ingress
          service: router-internal-default
          servicePort: 443
