kind: ConfigMap
apiVersion: v1
metadata:
  name: extended-spec-config
  namespace: kube-system
  labels:
    f5type: virtual-server
    as3: "true"
data:
  extendedSpec: |
    mode: default
    externalClustersConfig:
    - clusterName: cluster1
      secret: default/kubeconfig1
    - clusterName: cluster2
      secret: default/kubeconfig2
    - clusterName: cluster3
      secret: default/kubeconfig3  